# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routetype',
            options={'verbose_name': '线路分类', 'verbose_name_plural': '线路分类'},
        ),
    ]
