# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetail_route'),
        ('route', '0002_auto_20190424_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baidu_baike', models.CharField(max_length=255, verbose_name='百科介绍')),
                ('attraction_port', models.CharField(max_length=255, verbose_name='景点')),
                ('img', models.ImageField(upload_to='imgae/%Y/%m', verbose_name='图片')),
                ('schedule', models.CharField(help_text='此字段为列表结构[[day1,[一点干啥，两点干啥,.....]],[day2,[]]]', max_length=2000, verbose_name='行程安排')),
                ('attraction', models.CharField(help_text='此字段为列表', max_length=1000, verbose_name='注意事项')),
            ],
            options={
                'verbose_name': '主题详细信息',
                'verbose_name_plural': '主题详细信息',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='旅行日期')),
                ('team_num', models.IntegerField(verbose_name='团队数量')),
                ('status', models.IntegerField(choices=[('bm', 1), ('ym', 0)], verbose_name='报名状态')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('max_num', models.IntegerField(verbose_name='最大人数')),
                ('now_num', models.IntegerField(verbose_name='当前人数')),
            ],
            options={
                'verbose_name': '报名队伍',
                'verbose_name_plural': '报名队伍',
            },
        ),
        migrations.CreateModel(
            name='TravelTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_type', models.CharField(choices=[('tc', '同城旅行'), ('dt', '短途旅行'), ('ct', '长途旅行'), ('zt', '主题旅行')], max_length=4, verbose_name='旅行分类')),
                ('title', models.CharField(max_length=50, verbose_name='主题名称')),
                ('days', models.IntegerField(verbose_name='所需时间')),
                ('route', models.CharField(help_text='此字段所输入类型为列表', max_length=255, verbose_name='路线')),
                ('power', models.IntegerField(default=3, verbose_name='体力')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
                ('describe', models.CharField(help_text='此字段用于主页', max_length=50, verbose_name='主题描述')),
                ('introduce', models.CharField(max_length=255, verbose_name='主题简介')),
                ('mouth', models.IntegerField(verbose_name='出发月份')),
                ('img', models.ImageField(upload_to='imgae/%Y/%m', verbose_name='图片')),
                ('station', models.CharField(help_text='同城旅行为local，短途旅行为area，长途旅行直接输入区域', max_length=10, verbose_name='旅行地点')),
                ('click_num', models.IntegerField(verbose_name='点击数量')),
            ],
            options={
                'verbose_name': '旅行主题',
                'verbose_name_plural': '旅行主题',
            },
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='details',
        ),
        migrations.RemoveField(
            model_name='feedescription',
            name='details',
        ),
        migrations.RemoveField(
            model_name='route',
            name='type',
        ),
        migrations.RemoveField(
            model_name='routedetails',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routeintro',
            name='details',
        ),
        migrations.RemoveField(
            model_name='routeplan',
            name='details',
        ),
        migrations.RemoveField(
            model_name='travelteam',
            name='route',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='FeeDescription',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteDetails',
        ),
        migrations.DeleteModel(
            name='RouteIntro',
        ),
        migrations.DeleteModel(
            name='RoutePlan',
        ),
        migrations.DeleteModel(
            name='RouteType',
        ),
        migrations.DeleteModel(
            name='TravelTeam',
        ),
        migrations.AddField(
            model_name='tours',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.TravelTheme', verbose_name='所属的主题'),
        ),
        migrations.AddField(
            model_name='themeinfo',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.TravelTheme', verbose_name='所属的主题'),
        ),
    ]
