# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20190427_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=10, verbose_name='城市')),
            ],
        ),
        migrations.RemoveField(
            model_name='tours',
            name='date',
        ),
        migrations.RemoveField(
            model_name='traveltheme',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='traveltheme',
            name='mouth',
        ),
        migrations.RemoveField(
            model_name='traveltheme',
            name='price',
        ),
        migrations.RemoveField(
            model_name='traveltheme',
            name='station',
        ),
        migrations.AddField(
            model_name='themeinfo',
            name='cost_state',
            field=models.CharField(default='', help_text='此字段为列表', max_length=1000, verbose_name='费用说明'),
        ),
        migrations.AddField(
            model_name='tours',
            name='end_time',
            field=models.CharField(default='', max_length=10, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='tours',
            name='go_off',
            field=models.CharField(default='', max_length=10, verbose_name='出发时间'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='area',
            field=models.CharField(default='', max_length=10, verbose_name='所在区域'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='fit_month',
            field=models.CharField(choices=[('0', '全部'), ('1', '一月'), ('2', '二月'), ('3', '三月'), ('4', '四月'), ('5', '五月'), ('6', '六月'), ('7', '七月'), ('8', '八月'), ('9', '九月'), ('10', '十月'), ('11', '十一月'), ('12', '十二月')], default='0', max_length=4, verbose_name='适宜月份'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='max_price',
            field=models.CharField(default=0, max_length=5, verbose_name='最高价格'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='min_price',
            field=models.CharField(default=0, max_length=5, verbose_name='最低价格'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='team_num',
            field=models.IntegerField(verbose_name='队伍编号'),
        ),
        migrations.AlterField(
            model_name='traveltheme',
            name='days',
            field=models.IntegerField(verbose_name='旅游天数'),
        ),
        migrations.AlterField(
            model_name='traveltheme',
            name='describe',
            field=models.CharField(help_text='此字段用于主页', max_length=100, verbose_name='主题描述'),
        ),
    ]
