# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20190430_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltheme',
            name='power',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2, verbose_name='体力'),
        ),
    ]
