# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_auto_20190430_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltheme',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
    ]
