# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20190430_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltheme',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.City', verbose_name='所在区域'),
        ),
    ]
