# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20190430_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '所属区域', 'verbose_name_plural': '所属区域'},
        ),
        migrations.AlterModelOptions(
            name='themeinfo',
            options={'verbose_name': '主题详细', 'verbose_name_plural': '主题详细'},
        ),
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(max_length=10, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='traveltheme',
            name='describe',
            field=models.CharField(help_text='此字段用于主页,最大长度为255', max_length=255, verbose_name='主题描述'),
        ),
    ]
