# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20190430_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltheme',
            name='theme_intro',
            field=models.CharField(default='', help_text='最大长度为100', max_length=100, verbose_name='主题简介'),
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='theme_type',
            field=models.CharField(default='', max_length=20, verbose_name='主题类别'),
        ),
        migrations.AlterField(
            model_name='traveltheme',
            name='route',
            field=models.CharField(help_text='字段之间请以逗号相隔', max_length=255, verbose_name='路线'),
        ),
    ]
