# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_auto_20190430_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeinfo',
            name='img',
            field=models.ImageField(upload_to='details_img/%Y/%m', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='end_time',
            field=models.CharField(default='', help_text='格式:月-日', max_length=10, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='go_off',
            field=models.CharField(default='', help_text='格式:月-日', max_length=10, verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='now_num',
            field=models.IntegerField(default=0, verbose_name='当前人数'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='status',
            field=models.IntegerField(choices=[('1', '报名'), ('0', '已满')], verbose_name='报名状态'),
        ),
    ]
