# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_auto_20190501_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltheme',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='traveltheme',
            name='min_price',
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='price',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='每个数字代表一个价格', verbose_name='价格'),
        ),
    ]
