# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_auto_20190501_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltheme',
            name='price',
            field=models.CharField(default='0', max_length=50, verbose_name='价格区间'),
        ),
    ]
