# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_auto_20190501_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('1', '同城'), ('2', '短途'), ('3', '长途')], default='1', max_length=20, verbose_name='路线类型'),
        ),
    ]
