# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0013_city_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('tc', '同城'), ('dt', '短途'), ('ct', '长途'), ('zt', '主题旅行')], default='1', max_length=20, verbose_name='路线类型'),
        ),
    ]
