# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0014_auto_20190502_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltheme',
            name='concrete_price',
            field=models.IntegerField(default=1000, verbose_name='具体价格'),
        ),
    ]
