# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_traveltheme_concrete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='status',
            field=models.IntegerField(choices=[(1, '报名'), (0, '已满')], verbose_name='报名状态'),
        ),
    ]
