# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0017_remove_city_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveltheme',
            name='concrete_price',
        ),
        migrations.AddField(
            model_name='traveltheme',
            name='price_range',
            field=models.CharField(choices=[('1', '1000以下'), ('2', '1000-2000'), ('3', '2000-3000'), ('4', '3000-4000'), ('5', '4000以上')], default='0', max_length=50, verbose_name='价格区间'),
        ),
        migrations.AlterField(
            model_name='traveltheme',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='具体价格'),
        ),
    ]
