# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0018_auto_20190514_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltheme',
            name='price_range',
            field=models.CharField(choices=[('1', '1000以下'), ('2', '1000-2000'), ('3', '2000-3000'), ('4', '3000-4000'), ('5', '4000以上')], default='1', max_length=50, verbose_name='价格区间'),
        ),
    ]
