# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='route',
        ),
    ]
