# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20190427_1739'),
        ('orders', '0002_remove_orderdetail_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.ThemeInfo', verbose_name='线路'),
        ),
    ]
