# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_orderdetail_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='orderbuddy',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='route',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_tours',
            field=models.IntegerField(help_text='关联旅行队伍', null=True, verbose_name='订单所属主题'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单所属人'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(help_text='0:已提交，1：已付款，2：已退款', null=True, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='travel_buddy',
            field=models.CharField(help_text='列表形式[id1,id2.....],关联Userman', max_length=50, null=True, verbose_name='出行人'),
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
        migrations.DeleteModel(
            name='OrderBuddy',
        ),
    ]
