# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_teamorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamorder',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='teamorder',
            name='remarks',
            field=models.CharField(max_length=50, verbose_name='备注'),
        ),
    ]
