# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190430_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamorder',
            options={'verbose_name': '团队定制', 'verbose_name_plural': '团队定制'},
        ),
    ]
