# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190430_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamorder',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teamorder',
            name='remarks',
            field=models.CharField(help_text='最长字段为50', max_length=50, verbose_name='备注'),
        ),
    ]
