# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190501_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='theme',
            field=models.CharField(default='', max_length=10, verbose_name='订单所属主题'),
        ),
    ]
