# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderdetail_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='tour',
            field=models.CharField(default='', max_length=10, verbose_name='队伍id'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_tours',
            field=models.IntegerField(help_text='关联旅行队伍', null=True, verbose_name='队伍编号'),
        ),
    ]
