# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190508_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='end_time',
            field=models.CharField(default='', max_length=20, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='go_off',
            field=models.CharField(default='', max_length=20, verbose_name='出发时间'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='队伍主题'),
        ),
    ]
