# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190508_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(default='', max_length=10, verbose_name='价格'),
        ),
    ]
