# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '已支付'), (2, '已取消')], help_text='0:待付款，1：已支付，2：已取消', null=True, verbose_name='订单状态'),
        ),
    ]
